In [2]:
import pandas as pd

main_df = pd.read_parquet('Tatu main data-traficom_open_data_for_vehicles/') 
pred_price_df = pd.read_parquet('tatu data-tax_data_with_price_predictions/')  

main_df.to_parquet('main_data')
pred_price_df.to_parquet('pred_data')

In [8]:
main_df.columns

Index(['vehicle_classification', 'date_of_first_registration',
       'vehicle_subclass', 'usage', 'variant_uid', 'version_uid',
       'date_of_use', 'color', 'n_doors', 'body_type', 'cab_type', 'n_seats',
       'mass', 'manufac_perm_max_mass', 'max_road_perm_laden_mass',
       'length_mm', 'width_mm', 'height_mm', 'drive_power', 'engine_capacity',
       'max_net_engine_power_kw', 'sylintereidenLkm', 'supercharged',
       'electric_hybrid', 'electric_hybrid_cat', 'make_plaintext', 'model',
       'transmission', 'n_forward_gears', 'manufac_trade_name',
       'brake_transmission', 'type_approval_number', 'driving_power_euro_vi',
       'municipality', 'NEDC_Co2', 'NEDC2_Co2', 'WLTP_Co2', 'WLTP2_Co2',
       'odometer', 'serial_number_10', 'seq_number'],
      dtype='object')

In [22]:
=main_df['make_plaintext'] + main_df['model']

In [24]:
main_df['new'].unique()

array(['KymcoZING 125-RF25AC/124', 'BMWR60/590', 'SpriteALPINE/C', ...,
       'Mercedes-Benzsprinter  4ov 1950cm3 A',
       'BentleyContinental GT S V8 Coupé (AD) 2ov 3996cm3 A',
       'ToyotaLAND CRUISER S-HDJ81V Monikäyttöajoneuvo (AF) 5ov 4163cm3 A'],
      dtype=object)

In [5]:
main_df.rename(columns={'make_plaintext': 'make'}, inplace=True)

In [34]:
common_columns = ['make', 'model']

merged_df1 = pd.merge(main_df, pred_price_df[['make', 'model', 'date_of_first_registration', 'pred_price']],
                     how='left', on=common_columns)

MemoryError: Unable to allocate 900. MiB for an array with shape (15, 7861950) and data type object

In [11]:
merged_df1.rename(columns={'pred_price': 'price'}, inplace=True)

merged_df1['price'].isna()

Rows with missing prices after merge: 5364892

In [13]:
merged_df1

,vehicle_classification,date_of_first_registration_x,vehicle_subclass,usage,variant_uid,version_uid,date_of_use,color,n_doors,body_type,...,municipality,NEDC_Co2,NEDC2_Co2,WLTP_Co2,WLTP2_Co2,odometer,serial_number_10,seq_number,date_of_first_registration_y,price
0,L3,2003-06-10,109.0,1.0,None,None,2003-06-10,0,NaN,None,...,297,NaN,NaN,NaN,NaN,NaN,None,1,NaT,NaN
1,MUU,NaT,21.0,1.0,None,None,NaT,None,NaN,None,...,091,NaN,NaN,NaN,NaN,NaN,None,2,NaT,NaN
2,MUU,1976-09-01,13.0,1.0,None,None,NaT,None,NaN,None,...,475,NaN,NaN,NaN,NaN,NaN,None,3,NaT,NaN
3,M1,1984-07-09,NaN,1.0,None,None,NaT,1,NaN,None,...,740,NaN,NaN,NaN,NaN,NaN,None,4,NaT,NaN
4,MUU,1983-09-22,13.0,1.0,None,None,NaT,None,NaN,None,...,734,NaN,NaN,NaN,NaN,NaN,None,5,NaT,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5373787,M1G,2024-06-28,NaN,1.0,None,None,1992-05-04,0,5.0,AF,...,245,NaN,NaN,NaN,NaN,430463.0,None,5373619,NaT,NaN
5373788,O4,2024-06-28,14.0,6.0,None,None,2024-06-28,None,NaN,DA,...,091,NaN,NaN,NaN,NaN,NaN,None,5373620,NaT,NaN
5373789,M1,2024-06-28,NaN,1.0,ZWBF,ZWBFUD0?,2020-03-12,0,5.0,AC,...,790,NaN,42.0,NaN,45.0,64782.0,YV1ZWBFUDL,5373621,NaT,NaN
5373790,M1,2024-06-28,NaN,1.0,75D,B21B5N,2018-12-27,0,5.0,AB,...,604,NaN,NaN,NaN,NaN,88906.0,5YJSA7E20J,5373622,NaT,NaN
5373791,M1,2024-06-28,NaN,1.0,4,DGZU-C1J000,2021-02-08,0,5.0,AF,...,091,NaN,35.0,NaN,31.0,68935.0,VF3M4DGZUM,5373623,NaT,NaN

In [23]:
print(main_df['make'].unique(), main_df['model'].unique())
print(pred_price_df['make'].unique(),pred_price_df['model'].unique())

['Kymco' 'BMW' 'Sprite' ... 'Marlin' 'BENZINA ZERO' 'EASY CARAVANNING'] ['ZING 125-RF25AC/124' 'R60/590' 'ALPINE/C' ... 'sprinter  4ov 1950cm3 A'
 'Continental GT S V8 Coupé (AD) 2ov 3996cm3 A'
 'LAND CRUISER S-HDJ81V Monikäyttöajoneuvo (AF) 5ov 4163cm3 A']
['ADRIA' 'ALFA ROMEO' 'Alfa Romeo' 'AMC' 'Audi' 'AUDI' 'Bentley' 'BERTONE'
 'BMW' 'Bmw' 'bmw' 'CADILLAC' 'Cadillac' 'CHEVROLET' 'CHRYSLER' 'Chrysler'
 'CITROEN' 'Citroen' 'CLEVER' 'DACIA' 'DAIHATSU' 'DATSUN' 'DE SOTO'
 'Dethleffs' 'Dodge' 'DODGE' 'FERRARI' 'Fiat' 'FIAT'
 'FIAT DETHLEFFS 6910I' 'Fiat-Challenger' 'FISKER' 'Ford' 'FORD' 'ford'
 'FORD TRANSIT' 'GEELY' 'HONDA' 'Honda' 'Hymer' 'HYUNDAI' 'Hyundai'
 'INZILE' 'ISUZU' 'IVECO' 'JAGUAR' 'Jaguar' 'JEEP' 'Jeep' 'KARMA'
 'KARMA AUTOMOTIVE LLC' 'KARMANN MOBIL' 'KIA' 'Kia' 'LADA' 'LANCIA'
 'Land Rover' 'LAND ROVER' 'Lexus' 'LEXUS' 'MAN' 'MASERATI' 'Maserati'
 'MAZDA' 'Mazda' 'MCLAREN' 'Mercedes benz' 'Mercedes Benz'
 'Mercedes -Benz' 'Mercedes-Benz' 'MERCEDES-BENZ' 'mercedes-benz'
 'mercerdes-benz' 'mercury' 'MERSEDES-BENZ' 'MINI' 'Mini' 'MITSUBISHI'
 'Mitsubishi' 'NISSAN' 'Nissan' 'OPEL' 'Opel' 'PEUGEOT' 'PILOTE' 'Pilote'
 'PLYMOUTH' 'POLESTAR' 'Polestar' 'PONTIAC' 'PORSCHE' 'Porsche' 'RENAULT'
 'Renault' 'SAAB' 'Saab' 'SCANIA' 'SEAT' 'Seat' 'SKODA' 'Skoda' 'SMART'
 'SUBARU' 'Subaru' 'Suzuki' 'SUZUKI' 'TESLA' 'Tesla' 'tesla' 'tESLA'
 'Tesla Motors' 'TOYOTA' 'Toyota' 'toyota' 'TRIUMPH' 'WEINSBERG' 'VOLGA'
 'VOLKSWAGEN' 'Volkswagen' 'VOLVO' 'Volvo' ' CADILLAC' 'ASTON MARTIN'
 'BENTLEY' 'BINZ' 'BMW I' 'CUPRA' 'DETHLEFFS' 'DS' 'DS3' 'FIAT DUCATO'
 'FORD MUSTANG' 'GMC' 'HYMER' 'LINCOLN' 'LOTUS' 'LYNK&CO' 'MAXUS'
 'MERCURY' 'MG' 'POLESTAR 2' 'PÖSSL' 'ROVER' 'BUICK' 'LAMBORGHINI'
 'BENTLEY C' 'FAW' 'INFINITI' 'MAYBACH' 'MERCEDES BENZ' 'IZ' 'OLDSMOBILE'
 'ROLLS-ROYCE' 'TRABANT' 'TVR' 'VAUXHALL ' 'BMW ALPINA' 'MB'
 'MERCEDES-AMG' 'SSANGYONG' 'VAUXHALL' 'MC LAREN' 'SAAB 9-3'
 'ADRIA SONIC 700 SL' 'AL KO ARCA EUROPA 530' 'BYD' 'CARADO' 'CHALLENGER'
 'CHEROLET' 'CUBRA' 'LMC' 'LYNK & CO' 'MERCEDES -BENZ' 'MERCEDEZ BENZ'
 'PONTIAC FIREBIRD' 'RANGE ROVER' 'ROLLS ROYCE' 'VW' 'FISKER KARMA'
 'RANGE-ROVER' 'CATERHAM' 'KTM' 'INFINITY' 'MOSKVITZ' 'CARBODIES' 'DAEWOO'
 'ACURA' 'POLSKI FIAT' 'PUCH' 'Adria' 'Audi a8' 'Bmw Alpina' 'BMW-Alpina'
 'BRAVIA' 'buick' 'Buick' 'cadillac' 'Chevrolet' 'chevrolet' 'chrysler'
 'citroen' 'Datsun' 'dodge' 'Ferrari' 'FIAT ADRIA' 'FIAT KNAUS'
 'FIAT Sun Living' 'fiat Sunlight' 'FORD TDMCHS/5 (120-2,5)' 'GAZ' 'GLSC'
 'Ikarus' 'INTERNATIONAL' 'Isuzu' 'Knaus' 'Lada' 'Lincoln'
 'LONDON TAXIS INTERNATIONAL' 'mercedes benz' 'Mersedes Benz' 'Mg'
 'Morgan' 'Oldsmobile' 'opel' 'Plymouth' 'Pontiac' 'renault' 'Rolls Royce'
 'saab' 'Saturn' 'triumph' 'Vauxhall' 'Weinsberg' 'Volga' 'volkswagen'
 'volvo' 'Volvo XC90 T8 Twin Engine' 'LONDON TAXI'] ['ADRIAATIK 687 SP' 'GIULIA' 'MITO' ... 'G 270 CDI' 'Alto'
 'Transporter Caravelle']

In [32]:
main_df['make'] = main_df['make'].str.strip().str.lower()
pred_price_df['make'] = pred_price_df['make'].str.strip().str.lower()

main_df['model'] = main_df['model'].str.strip().str.lower()
pred_price_df['model'] = pred_price_df['model'].str.strip().str.lower()

print(main_df[['make', 'model', 'date_of_first_registration']].isna().sum())
print(pred_price_df[['make', 'model', 'date_of_first_registration']].isna().sum())

make                            1891
model                         921502
date_of_first_registration    171487
dtype: int64
make                              0
model                           966
date_of_first_registration    23264
dtype: int64

In [26]:
main_df.rename(columns={'make_plaintext': 'make'}, inplace=True)

In [28]:
main_df['make']=main_df['make'].str.lower()

In [30]:
main_df['model']=main_df['model'].str.lower()
pred_price_df['model']=main_df['model'].str.lower()
pred_price_df['model']=main_df['model'].str.lower()